######################## configuração básica ####################
baseURL = "http://localhost:1313/"
title = "Departamento de Engenharia de Sistemas e Computação"
theme = "educenter-hugo"

defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = false
enableGitInfo = true

[frontmatter]
lastmod = [":git", "lastmod", "date", "publishDate"]

############################ paginação ##########################
[pagination]
pagerSize = 6

summaryLength = 10

############################ parâmetros #########################
[params]
logo = "images/logodesc.png"
description = "Site do Departamento de Engenharia de Sistemas e Computação"
author = "João Araujo"

address = "Rua São Francisco Xavier, 524, Maracanã, Rio de Janeiro"
mobile = "indisponível"
email = "secretaria.desc@eng.uerj.br"
echefia = "desc@eng.uerj.br"

top_header = true
chefia = "Felipe Ulrichsen"
subchefia = "Robert Mota"
chefialab = "Giomar Sequeiros"
coordenadorprojeto = "João Araujo"
secretaria = ""

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################ menus ##############################
[[menu.main]]
name = "Disciplinas"
url = "course"
weight = 1

[[menu.main]]
name = "Horário"
url = "horarios"
weight = 2

[[menu.main]]
name = "TCC"
url = "tcc"
weight = 3

[[menu.main]]
name = "Sobre o DESC"
weight = 4
hasChildren = true

  [[menu.main]]
  parent = "Sobre o DESC"
  name = "Histórico"
  url = "about/historico"

  [[menu.main]]
  parent = "Sobre o DESC"
  name = "Perfil do Egresso"
  url = "about/perfil_do_egresso"

  [[menu.main]]
  parent = "Sobre o DESC"
  name = "Professores"
  url = "teacher"

  [[menu.main]]
  parent = "Sobre o DESC"
  name = "Concursos"
  url = "about/concursos"

  [[menu.main]]
  parent = "Sobre o DESC"
  name = "Administração"
  url = "contact/administrativo"

[[menu.main]]
name = "Contato"
url = "contact"
weight = 5

############################ footer #############################
[[menu.footer]]
name = "Professores"
url = "teacher"

[[menu.footer]]
name = "Histórico"
url = "about/historico"

[[menu.footer]]
name = "Perfil do Egresso"
url = "about/perfil_do_egresso"

[[menu.footer]]
name = "Concursos"
url = "about/concursos"

[[menu.footer]]
name = "Pesquisa"
url = "research"
